### PR TITLE
Add support for Symfony 5

### PR DESCRIPTION
**Pull request by biozshock**
Bug fix? | no
-- | --
New feature? | an enhancement in term of supported deps
BC breaks? | no
Deprecations? | no
Fixed tickets | none
License | MIT

**Description**
Added support for Symfony 5.

### CODE REVIEW

**Comment by chekalsky** [comment]
@romainneutron Hi, when do you plan to merge it and release a new version?

**Comment by biozshock** [comment]
Probably @jens1o is proper person to ask now?

**Comment by biozshock** [comment]
@jens1o can we please merge this one or #14 or #15  ?
Q: Why silencing in tests?
A: Because we support php 5.6, which have no return types, and version where PHPUnit was fixed requires 7.2 and has return type in setUp method.

**Comment by biozshock** [comment]
closed in favor of #15

**Pull request closed without merging**
