### PR TITLE
Add Symfony 6.0 support

### PR DESCRIPTION
**Pull request by javer**

### CODE REVIEW

**Comment by javer** [comment]
@romainneutron @jens1o Could you please review this PR?

**Review by jens1o — APPROVED** [review]
Thanks for the pull request. :)

Diff LGTM

**Comment by javer** [comment]
@jens1o Thank you! Could you please tag a release? Something compatible with ^3.0, because there are no BC breaks here.

**Comment by jens1o** [comment]
I've tagged a new release, sorry for the wait. :)

**Pull request merged**
